---
- name: Ensuring config directories exist
  file:
    path: "{{ node_config_directory }}/{{ item }}"
    state: "directory"
    recurse: yes
    mode: "u=rwx,g=rwx,o="
  with_items:
    - "memcached"

- name: Copying over config.json files for services
  template:
    src: "{{ item }}.json.j2"
    dest: "{{ node_config_directory }}/{{ item }}/config.json"
    mode: "u=rw,g=rw,o="
  register: memcached_config_json
  with_items:
    - "memcached"
  notify: Restart memcached container

- name: Check memcached container
  vars:
    service: "{{ memcached_services.memcached }}"
  kolla_docker:
    action: "compare_container"
    common_options: "{{ docker_common_options }}"
    name: "{{ service.container_name }}"
    image: "{{ service.image }}"
    volumes: "{{ service.volumes }}"
  register: check_memcached_container
  when:
    - inventory_hostname in groups[service.group]
    - service.enabled | bool
    - action != "config"
  notify: Restart memcached container

- name: Ensuring config directories have correct owner and permission
  become: yes
  file:
    path: "{{ node_config_directory }}/{{ item }}"
    recurse: yes
    owner: "{{ config_owner_user }}"
    group: "{{ config_owner_group }}"
  with_items:
    - "memcached"

