---
- name: Ensuring config directories exist
  file:
    path: "{{ node_config_directory }}/{{ item }}"
    state: "directory"
    recurse: yes
    mode: "u=rwx,g=rwx,o="
  with_items:
    - "rabbitmq"

- name: Copying over config.json files for services
  template:
    src: "{{ item }}.json.j2"
    dest: "{{ node_config_directory }}/{{ item }}/config.json"
    mode: "u=rwx,g=rwx,o="
  with_items:
    - "rabbitmq"

- name: Copying over rabbitmq configs
  template:
    src: "{{ item }}.j2"
    dest: "{{ node_config_directory }}/rabbitmq/{{ item }}"
    mode: "u=rwx,g=rwx,o="
  with_items:
     - "rabbitmq-env.conf"
     - "rabbitmq.config"
     - "rabbitmq-clusterer.config"
     - "definitions.json"

- name: Ensuring config directories have correct owner and permission
  become: yes
  file:
    path: "{{ node_config_directory }}/{{ item }}"
    recurse: yes
    owner: "{{ config_owner_user }}"
    group: "{{ config_owner_group }}"
  with_items:
    - "rabbitmq"
