---
- name: Setting sysctl values
  become: true
  sysctl: name={{ item.name }} value={{ item.value }} sysctl_set=yes
  with_items:
    - { name: "net.ipv4.ip_nonlocal_bind", value: 1}
    - { name: "net.unix.max_dgram_qlen", value: 128}
  when: set_sysctl | bool

- name: Ensuring config directories exist
  file:
    path: "{{ node_config_directory }}/{{ item }}"
    state: "directory"
    recurse: yes
    mode: "u=rwx,g=rwx,o="
  with_items:
    - "keepalived"
    - "haproxy"

- name: Copying over config.json files for services
  template:
    src: "{{ item }}.json.j2"
    dest: "{{ node_config_directory }}/{{ item }}/config.json"
    mode: "u=rw,g=rw,o="
  with_items:
    - "keepalived"
    - "haproxy"

- name: Copying over haproxy.cfg
  template:
    src: "{{ item }}"
    dest: "{{ node_config_directory }}/haproxy/haproxy.cfg"
    mode: "u=rw,g=rw,o="
  with_first_found:
    - "{{ node_custom_config }}/haproxy/{{ inventory_hostname }}/haproxy.cfg"
    - "{{ node_custom_config }}/haproxy/haproxy.cfg"
    - "haproxy.cfg.j2"

- name: Copying over keepalived.conf
  template:
    src: "{{ item }}"
    dest: "{{ node_config_directory }}/keepalived/keepalived.conf"
    mode: "u=rw,g=rw,o="
  with_first_found:
    - "{{ node_custom_config }}/keepalived/{{ inventory_hostname }}/keepalived.conf"
    - "{{ node_custom_config }}/keepalived/keepalived.conf"
    - "keepalived.conf.j2"

- name: Copying over haproxy.pem
  copy:
    src: "{{ kolla_external_fqdn_cert }}"
    dest: "{{ node_config_directory }}/haproxy/{{ item }}"
    mode: "u=rw,g=rw,o="
  with_items:
    - "haproxy.pem"
  when: kolla_enable_tls_external | bool

- name: Ensuring config directories have correct owner and permission
  become: yes
  file:
    path: "{{ node_config_directory }}/{{ item }}"
    recurse: yes
    owner: "{{ config_owner_user }}"
    group: "{{ config_owner_group }}"
  with_items:
    - "keepalived"
    - "haproxy"
