---
- name: Creating admin openrc file on the deploy node
  become: true
  hosts: all
  tasks:
    - template:
        src: "roles/common/templates/admin-openrc.sh.j2"
        dest: "{{ node_config_directory }}/admin-openrc.sh"
        group: "{{ config_owner_group }}"
        mode: "u=rw,g=rw,o="
      run_once: True
      connection: local
